print('Hi\nI am new to Python')
print('')
print('My favourite animals are dogs')
print('o-###-')
print('. | |')
print('')
print('I live in Toronto')
print('      |')
print('      =.  HOME IS')
print('      |   T O R O N T O ')
print('      | ')
print('     / \ ')
print('')
print('Here is a scarf:')
print('~#' * 10)
print('#~' * 10)
print('Hre is a wave:')
print('/\  ' * 10)
print('  \/' * 9)
print('')
age = input('What is your age?')
dog = int(age)
dog_age = dog *7
print("If you were a dog you'd be", dog_age, "years old!")

